

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sem3Project.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class NorthwindEntities : DbContext
{
    public NorthwindEntities()
        : base("name=NorthwindEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Card> Cards { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Order_Detail> Order_Details { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<Shipper> Shippers { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Territory> Territories { get; set; }


    public virtual int usp_MaintainCategoryPage(string pageSearch, string sortOrder, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {

        var pageSearchParameter = pageSearch != null ?
            new ObjectParameter("PageSearch", pageSearch) :
            new ObjectParameter("PageSearch", typeof(string));


        var sortOrderParameter = sortOrder != null ?
            new ObjectParameter("SortOrder", sortOrder) :
            new ObjectParameter("SortOrder", typeof(string));


        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MaintainCategoryPage", pageSearchParameter, sortOrderParameter, pageIndexParameter, pageSizeParameter, recordCount);
    }


    public virtual int usp_MaintainEmployeePage(string pageSearch, string sortOrder, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {

        var pageSearchParameter = pageSearch != null ?
            new ObjectParameter("PageSearch", pageSearch) :
            new ObjectParameter("PageSearch", typeof(string));


        var sortOrderParameter = sortOrder != null ?
            new ObjectParameter("SortOrder", sortOrder) :
            new ObjectParameter("SortOrder", typeof(string));


        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MaintainEmployeePage", pageSearchParameter, sortOrderParameter, pageIndexParameter, pageSizeParameter, recordCount);
    }


    public virtual int usp_MaintainOrderDetailsPage(string pageSearch, Nullable<int> orderID, string sortOrder, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {

        var pageSearchParameter = pageSearch != null ?
            new ObjectParameter("PageSearch", pageSearch) :
            new ObjectParameter("PageSearch", typeof(string));


        var orderIDParameter = orderID.HasValue ?
            new ObjectParameter("OrderID", orderID) :
            new ObjectParameter("OrderID", typeof(int));


        var sortOrderParameter = sortOrder != null ?
            new ObjectParameter("SortOrder", sortOrder) :
            new ObjectParameter("SortOrder", typeof(string));


        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MaintainOrderDetailsPage", pageSearchParameter, orderIDParameter, sortOrderParameter, pageIndexParameter, pageSizeParameter, recordCount);
    }


    public virtual int usp_MaintainOrderPage(string pageSearch, string sortOrder, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {

        var pageSearchParameter = pageSearch != null ?
            new ObjectParameter("PageSearch", pageSearch) :
            new ObjectParameter("PageSearch", typeof(string));


        var sortOrderParameter = sortOrder != null ?
            new ObjectParameter("SortOrder", sortOrder) :
            new ObjectParameter("SortOrder", typeof(string));


        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MaintainOrderPage", pageSearchParameter, sortOrderParameter, pageIndexParameter, pageSizeParameter, recordCount);
    }


    public virtual int usp_MaintainProductPage(string pageSearch, string sortOrder, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {

        var pageSearchParameter = pageSearch != null ?
            new ObjectParameter("PageSearch", pageSearch) :
            new ObjectParameter("PageSearch", typeof(string));


        var sortOrderParameter = sortOrder != null ?
            new ObjectParameter("SortOrder", sortOrder) :
            new ObjectParameter("SortOrder", typeof(string));


        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MaintainProductPage", pageSearchParameter, sortOrderParameter, pageIndexParameter, pageSizeParameter, recordCount);
    }


    public virtual int usp_MaintainShipperPage(string pageSearch, string sortOrder, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {

        var pageSearchParameter = pageSearch != null ?
            new ObjectParameter("PageSearch", pageSearch) :
            new ObjectParameter("PageSearch", typeof(string));


        var sortOrderParameter = sortOrder != null ?
            new ObjectParameter("SortOrder", sortOrder) :
            new ObjectParameter("SortOrder", typeof(string));


        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MaintainShipperPage", pageSearchParameter, sortOrderParameter, pageIndexParameter, pageSizeParameter, recordCount);
    }


    public virtual ObjectResult<usp_Report_Result> usp_Report(Nullable<System.DateTime> beginning_Date, Nullable<System.DateTime> ending_Date)
    {

        var beginning_DateParameter = beginning_Date.HasValue ?
            new ObjectParameter("Beginning_Date", beginning_Date) :
            new ObjectParameter("Beginning_Date", typeof(System.DateTime));


        var ending_DateParameter = ending_Date.HasValue ?
            new ObjectParameter("Ending_Date", ending_Date) :
            new ObjectParameter("Ending_Date", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_Result>("usp_Report", beginning_DateParameter, ending_DateParameter);
    }


    public virtual int usp_UpdateData()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateData");
    }


    public virtual int usp_UpdateDataCate()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateDataCate");
    }


    public virtual int usp_UpdateDataEmployee()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateDataEmployee");
    }

}

}

